apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test2-devfile-sample-llwu-sample
  namespace: rhn-engineering-markmc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:755e4e3346c0ae2f6f49853126f0e45f78ebe0263b80d72df1b9de81a2bc3290
        name: container-image
        resources: {}
status: {}
